"""Add user_id in asset

Revision ID: 0fcb21aed860
Revises: 7fcbccb69f76
Create Date: 2021-11-21 19:22:59.612142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcb21aed860'
down_revision = '7fcbccb69f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'user_id')
    # ### end Alembic commands ###
