"""Add unique constraint (code, user_id) in asset

Revision ID: 2ebac442454b
Revises: 0fcb21aed860
Create Date: 2021-11-28 13:59:13.727647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebac442454b'
down_revision = '0fcb21aed860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_code_key', 'asset', type_='unique')
    op.create_unique_constraint('unique__code__user_id', 'asset', ['code', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique__code__user_id', 'asset', type_='unique')
    op.create_unique_constraint('asset_code_key', 'asset', ['code'])
    # ### end Alembic commands ###
