"""Add is_purchase in asset entry

Revision ID: 8aff33beedc5
Revises: dcc0d2c55b31
Create Date: 2021-12-15 22:47:35.174576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aff33beedc5'
down_revision = 'dcc0d2c55b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_entry', sa.Column('is_purchase', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_entry', 'is_purchase')
    # ### end Alembic commands ###
